// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔒 SÉCURISÉ : Utilisation des variables d'environnement
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bwljyrhvhumqtsmakavm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bGp5cmh2aHVtcXRzbWFrYXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjgxOTUsImV4cCI6MjA2Mzg0NDE5NX0.KJdotwFAAy3o-cQlIwm2mAi3yCx8tfCRBtWtfdTCdbY";

// Validation des variables d'environnement
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Variables d\'environnement Supabase manquantes. Vérifiez votre fichier .env.local');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);